### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by EmmanuelVella** [symfony-cmf/MenuBundle#169]
Hi,

I have a memory issue with the menus when running my behat 92 scenarios. I set the cli memory limit to 512MB during the tests.

Without menus displayed, the memory peak is 170MB
With menus displayed, the memory peak is 470MB

With a lower memory limit (256MB), the tests crash.

I use the stable versions of the cmf bundles.

**Comment by dbu** [comment]
what do we do with this one? can we reproduce it? does it go away with knp menu 2.0?

**Comment by WouterJ** [comment]
I cannot find major memory leaks when using a menu.

I think there is a memory leak in KnpMenu: https://github.com/KnpLabs/KnpMenu/blob/master/src/Knp/Menu/MenuItem.php#L347-L349 (both classes reference eachother), but at least the PHP 7 I installed locally is able to clean this up before hitting the memory limit.

**Comment by WouterJ** [comment]
Closing because of the lack of response. Feel free to comment if you have more details.
