### ISSUE TITLE
Log instead of quietly skipping

### ISSUE THREAD

**Issue by ElectricMaxxx** [symfony-cmf/MenuBundle#200]
I had to feel a little issue with the MenuFactory:
When referencing a content with multiple routes to a menu node the route can't be computed for the menu item. So it won't be displayed.

Looking through the code i found that this skipping isn't even logged:
https://github.com/symfony-cmf/MenuBundle/blob/master/ContentAwareFactory.php#L238

When there is an issue with the creation of the route for a content mapped to a menu node it isn't simply not displayed. 

Is there no chance to add a kind of voter to solve my multiple routes issue? At the moment i changed to the setting of the `uri` instead of referencing a content. Cause that situation can occur very often:

- creating a menu item referencing a content with one route 
- menu item is displayed well
- some admin decided to add a route to that content
- menu item disappears quit and nobody(admins) knows why

**Comment by WouterJ** [comment]
We do log now on error level, so I consider this closed: https://github.com/symfony-cmf/MenuBundle/blob/master/QuietFactory.php#L51 (unless I understand this wrongly)
