### ISSUE TITLE
Log critical error when the menu node does not implement NodeInterface

### ISSUE THREAD

**Issue by dantleech** [symfony-cmf/MenuBundle#213]
If a menu node is found by the provider, but does not implement the NodeInterface, then it is ignored - i.e. the same behavior as if the node were not found at all.

I think it is valid that we ignore not found documents (for the chain provider), I think if a document is found but it does not implement the interface we should throw a RuntimeError.

**Comment by WouterJ** [comment]
The QuietFactory is now logging the errors, so I think this is fixed. If I got it wrong, please reopen :)
