### ISSUE TITLE
Document cmf_menu.allow_empty_items configuration. 

### ISSUE THREAD

**Issue by brunoreis** [symfony-cmf/MenuBundle#216]
Since not matched routes do not appear on menu, filtered by ContentAwareFactory, it's a little tricky to know what is going on. So I have 2 suggstions to make first time users happier: 

1 - document the cmf_menu.allow_empty_items and make an alert note about items not showing for broken url/content. 

2 - make this configuration default to false, at least for dev envs.

**Comment by dbu** [comment]
see https://github.com/symfony-cmf/symfony-cmf-docs/pull/699
