### ISSUE TITLE
bug in QuietFactory

### ISSUE THREAD

**Issue by dbu** [symfony-cmf/MenuBundle#230]
the quiet factory seems to mess up on the allowEmptyItems option: https://github.com/symfony-cmf/MenuBundle/blob/master/QuietFactory.php#L57
we implicitly return null as well. the idea of allowing empty items would be to return a menu item with just the text but no URL.

**Comment by WouterJ** [comment]
Hmm, good catch. What text should used though, `$name`?

**Comment by dbu** [comment]
i think this is what was used previously yes: https://github.com/symfony-cmf/MenuBundle/blob/1.2/ContentAwareFactory.php#L269

it seems that knp menu 1 was ok to build without a url. if its super complicated, we could also just have a config whether to explode or ignore (and not show) menu items without url. and default that config to whether we are in dev or prod environment.

**Comment by WouterJ** [comment]
KnpMenu 2 is still capable of generating menu items without URL, for some reason I didn't implement it in the QuietFactory. Fixed it in #232
