### ISSUE TITLE
[Release Request] New release to add knp menu ^2.0

### ISSUE THREAD

**Issue by diimpp** [symfony-cmf/MenuBundle#236]
Hi guys,

Would be cool to have new release to have a knp menu ^2.0 dep.
I'm coming from sylius content bundle, which uses latest stable version of this bundle, which uses knp menu ~1.1, which isn't installable on latest symfony 2.7+ :)

Regards,
Dmitri.

**Comment by WouterJ** [comment]
I've just released 2.0.0-RC1, which will come with KnpMenu 2 support.

Please note that 1.x (of both KnpMenu and this bundle) support Symfony 2.7 and 2.8 just fine.

**Comment by diimpp** [comment]
Cool :) Thank you.
