### ISSUE TITLE
Confused about changes to AbstractMenuNodeAdmin

### ISSUE THREAD

**Issue by ConneXNL** [symfony-cmf/MenuBundle#240]
Since https://github.com/symfony-cmf/MenuBundle/commit/82dcec00a26cb29abe60a1b531cbb75b70f07af6 it seems Sonata admin bundle is only showing me  "auto" only for link type. Route, uri, content don't show up...

Additionally, I am no longer able to set a Route for a MenuNode, which is important for Breadcrumbs.

Am I missing something?

**Comment by WouterJ** [comment]
I can confirm this issue: http://sandbox.cmf.symfony.com/en/admin/cmf/menu/menunode/cms/menu/main/projects-item/cmf-item/edit

Seems like the `choices` option has to be reintroduced in order to fix this issue.

**Comment by WouterJ** [comment]
See https://github.com/symfony-cmf/MenuBundle/pull/245 for a fix
